### ISSUE TITLE
xview2 dataset

### ISSUE THREAD

**Issue by xdtl** [BloodAxe/Catalyst-Inria-Segmentation-Example#8]
I want to include xview2 dataset in training by setting data directory using "-dd-xview2", and got the following error. Could you please give me some suggestions on how to fix it? Thanks very much!

```
  File ".../Catalyst/lib/python3.7/site-packages/catalyst/core/runner.py", line 987, in run_experiment
    self._run_event("on_exception")
  File ".../Catalyst/lib/python3.7/site-packages/catalyst/core/runner.py", line 780, in _run_event
    getattr(callback, event)(self)
  File ".../Catalyst/lib/python3.7/site-packages/catalyst/core/callbacks/exception.py", line 24, in on_exception
    raise exception
  File ".../Catalyst/lib/python3.7/site-packages/catalyst/core/runner.py", line 975, in run_experiment
    self._run_stage(stage)
  File ".../Catalyst/lib/python3.7/site-packages/catalyst/core/runner.py", line 943, in _run_stage
    self._run_epoch(stage=stage, epoch=self.epoch)
  File ".../Catalyst/lib/python3.7/site-packages/catalyst/core/runner.py", line 922, in _run_epoch
    self._run_loader(loader)
  File ".../Catalyst/lib/python3.7/site-packages/catalyst/core/runner.py", line 854, in _run_loader
    for i, batch in enumerate(loader):
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File ".../Catalyst/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 218, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File ".../Catalyst/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 218, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File ".../BuildingSegmentation/inria/dataset.py", line 145, in __getitem__
    data = self.transform(image=image, mask=mask)
  File ".../Catalyst/lib/python3.7/site-packages/albumentations/core/composition.py", line 182, in __call__
    data = t(force_apply=force_apply, **data)
TypeError: 'list' object is not callable
python-BaseException```

**Comment by BloodAxe** [comment]
Greetings, it's hard to tell, from the stacktrace, but it seems there is type mismatch somewhere in xview2 dataset part. 
The code is under active refactoring at this point as I'm preparing pre-trained model zoo, which is likely to be released by the end of the year. So right now I can't provide support on this matter.

**Comment by xdtl** [comment]
Thank you for your reply! I am looking forward to the pre-trained model zoo!
